version: '3.8'

services:
  webapi:
    container_name: dotnet8_webapi
    build:
      context: .               # Build context is the root of your project
      dockerfile: Dockerfile   # Dockerfile path
    ports:
      - "5000:80"              # Map container port 80 to host port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql_db;Port=3306;Database=MyDatabase;User=root;Password=YourStrong!Passw0rd;
    depends_on:
      - mysql_db
    restart: always

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=MyDatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=Password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    

